# Generated by Django 4.2 on 2024-10-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_see_all_newsletters", "can see all newsletters"),
                    ("can_see_all_users", "can see all users"),
                    ("can_blocked_users", "can blocked users"),
                    ("can_cancel_newsletter", "can cancel newsletter"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
