# Generated by Django 4.2 on 2024-10-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_see_all_newsletters", "can see all newsletters"),
                    ("can_cancel_newsletter", "can cancel newsletter"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
