# Generated by Django 4.2 on 2024-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_alter_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Ф.И.О."
            ),
        ),
    ]
