# Generated by Django 4.2 on 2024-10-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="заголовок")),
                ("body", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="изображение"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="счетчик просмотров"),
                ),
                ("published_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "блоги",
            },
        ),
    ]
