# Generated by Django 4.2 on 2024-10-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "блог", "verbose_name_plural": "блоги"},
        ),
    ]
