# Generated by Django 4.2 on 2024-10-31 08:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=blog.models.blog_image_upload_path,
                verbose_name="изображение",
            ),
        ),
    ]
