# Generated by Django 4.2 on 2024-10-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/", verbose_name="изображение"
            ),
        ),
    ]
